/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/models/postwar_city/scene.gltf 
Author: Aurélien Martel (https://sketchfab.com/aurelien_martel)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/postwar-city-exterior-scene-30b694d1a4074855a1116a15a0f75731
Title: Postwar City - Exterior Scene
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function PostwarCity(props) {
  const { nodes, materials } = useGLTF('models/postwar_city/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={13.333}>
        <group rotation={[Math.PI / 2, Math.PI / 2, 0]}>
          <mesh geometry={nodes.TexturesCom_BuildingsDerelict0001_M_0.geometry} material={materials.TexturesCom_BuildingsDerelict0001_M} />
          <mesh geometry={nodes.TexturesCom_BuildingsDerelict0001_M_1.geometry} material={materials['cote-batiment.001']} />
        </group>
        <group position={[0.018, 0.439, 0.5]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
          <mesh geometry={nodes.TexturesCom_BuildingsHouseOld0007_M_0.geometry} material={materials.TexturesCom_BuildingsHouseOld0007_M} />
          <mesh geometry={nodes.TexturesCom_BuildingsHouseOld0007_M_1.geometry} material={materials['cote-batiment']} />
        </group>
        <group position={[-0.025, 0.888, 0.366]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.75}>
          <mesh geometry={nodes.TexturesCom_BuildingsHouseOld0005_M_0.geometry} material={materials.TexturesCom_BuildingsHouseOld0005_M} />
          <mesh geometry={nodes.TexturesCom_BuildingsHouseOld0005_M_1.geometry} material={materials['cote-batiment.002']} />
        </group>
        <group position={[1.18, -0.061, 0.494]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.TexturesCom_HighRiseResidential0035_S_0.geometry} material={materials.TexturesCom_HighRiseResidential0035_S} />
          <mesh geometry={nodes.TexturesCom_HighRiseResidential0035_S_1.geometry} material={materials['cote-batiment.004']} />
        </group>
        <group position={[1.217, 0.37, 0.347]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.601}>
          <mesh geometry={nodes.TexturesCom_BuildingsDerelict0068_S_0.geometry} material={materials.TexturesCom_BuildingsDerelict0068_S} />
          <mesh geometry={nodes.TexturesCom_BuildingsDerelict0068_S_1.geometry} material={materials['cote-batiment.005']} />
        </group>
        <group position={[1.129, 0.738, 0.494]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.443}>
          <mesh geometry={nodes.TexturesCom_BuildingsHouseOld0203_S_0.geometry} material={materials.TexturesCom_BuildingsHouseOld0203_S} />
          <mesh geometry={nodes.TexturesCom_BuildingsHouseOld0203_S_1.geometry} material={materials['cote-batiment.007']} />
        </group>
        <group position={[1.133, 0.773, 0.128]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.29}>
          <mesh geometry={nodes.TexturesCom_Shops0175_S_0.geometry} material={materials.TexturesCom_Shops0175_S} />
          <mesh geometry={nodes.TexturesCom_Shops0175_S_1.geometry} material={materials['cote-batiment.008']} />
        </group>
        <group position={[1.163, 1.354, 0.241]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.492}>
          <mesh geometry={nodes.TexturesCom_BuildingsDerelict0132_S_0.geometry} material={materials.TexturesCom_BuildingsDerelict0132_S} />
          <mesh geometry={nodes.TexturesCom_BuildingsDerelict0132_S_1.geometry} material={materials['cote-batiment.009']} />
        </group>
        <group position={[-0.02, 1.997, 0.421]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
          <mesh geometry={nodes.TexturesCom_BuildingsTallHouse0057_S_0.geometry} material={materials.TexturesCom_BuildingsTallHouse0057_S} />
          <mesh geometry={nodes.TexturesCom_BuildingsTallHouse0057_S_1.geometry} material={materials.auvent} />
          <mesh geometry={nodes.TexturesCom_BuildingsTallHouse0057_S_2.geometry} material={materials['cote-batiment.010']} />
        </group>
        <group position={[-4.679, 4.85, -0.002]} rotation={[0, -0.001, -0.398]} scale={0.062}>
          <mesh geometry={nodes['42526024016_0'].geometry} material={materials['wall.002']} position={[111.854, -8.497, -0.356]} />
          <mesh geometry={nodes['42526024015_0'].geometry} material={materials['wall.buidings.001']} position={[111.854, -8.497, -0.356]} />
          <mesh geometry={nodes['42526024014_0'].geometry} material={materials['wall.001']} position={[111.854, -8.497, -0.356]} />
          <mesh geometry={nodes['42526024012_0'].geometry} material={materials['wall.003']} position={[111.854, -8.497, -0.356]} />
          <mesh geometry={nodes['42526024011_0'].geometry} material={materials['wall.buidings']} position={[111.854, -8.497, -0.356]} />
          <mesh geometry={nodes['42526024010_0'].geometry} material={materials['wall.buidings.003']} position={[131.771, -43.72, -0.366]} />
          <mesh geometry={nodes['42526024009_0'].geometry} material={materials['wall.buidings.002']} position={[131.771, -43.72, -0.366]} rotation={[-0.002, 0.001, -Math.PI / 2]} />
          <mesh geometry={nodes['42526024008_0'].geometry} material={materials['wall.buidings.002']} position={[131.771, -43.72, -0.366]} rotation={[-0.002, 0.001, -Math.PI / 2]} />
          <mesh geometry={nodes['42526024007_0'].geometry} material={materials['wall.buidings.003']} position={[131.771, -43.72, -0.366]} />
          <mesh geometry={nodes['42526024006_0'].geometry} material={materials['wall.003']} position={[111.854, -8.497, -0.356]} />
          <mesh geometry={nodes['42526024005_0'].geometry} material={materials.wall} position={[111.854, -8.497, -0.356]} />
          <mesh geometry={nodes['42526024001_0'].geometry} material={materials.route} position={[111.854, -8.497, -0.301]} />
          <mesh geometry={nodes['42526024_0'].geometry} material={materials['wall.002']} position={[111.854, -8.497, -0.356]} />
        </group>
        <group position={[0.002, 1.563, 0.309]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.723}>
          <mesh geometry={nodes.TexturesCom_Buildings18thCentury0035_1_S_0.geometry} material={materials.TexturesCom_Buildings18thCentury0035_1_S} />
          <mesh geometry={nodes.TexturesCom_Buildings18thCentury0035_1_S_1.geometry} material={materials['cote-batiment.003']} />
        </group>
        <group position={[0.794, 1.057, 0.03]}>
          <mesh geometry={nodes.Cube006_0.geometry} material={materials.voiture} />
          <mesh geometry={nodes.Cube006_1.geometry} material={materials['glass-voiture']} />
          <mesh geometry={nodes.Cube006_2.geometry} material={materials['vide-voiture']} />
          <mesh geometry={nodes.Cube006_3.geometry} material={materials.jante} />
        </group>
        <group position={[0.215, 0.276, 0.034]} rotation={[0.003, 0.064, -2.786]}>
          <mesh geometry={nodes.Cube010_0.geometry} material={materials['voiture.001']} />
          <mesh geometry={nodes.Cube010_1.geometry} material={materials['glass-voiture.001']} />
          <mesh geometry={nodes.Cube010_2.geometry} material={materials['vide-voiture.001']} />
          <mesh geometry={nodes.Cube010_3.geometry} material={materials['jante.001']} />
        </group>
        <mesh geometry={nodes.TexturesCom_DoorsWoodPanelled0239_S_0.geometry} material={materials.TexturesCom_DoorsWoodPanelled0239_S} position={[0, 0.01, 0.078]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.152} />
        <mesh geometry={nodes.TexturesCom_Shops0244_S_0.geometry} material={materials.TexturesCom_Shops0244_S} position={[1.224, 0.371, 0.091]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.217} />
        <mesh geometry={nodes.TexturesCom_HighRiseTowers0146_S_0.geometry} material={materials.TexturesCom_HighRiseTowers0146_S} position={[1.147, 2.564, 0.915]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={1.83} />
        <mesh geometry={nodes.Circle_0.geometry} material={materials['trottoir.001']} position={[-0.133, 1.102, -0.008]} scale={0.052} />
        <mesh geometry={nodes.Cube_0.geometry} material={materials['paves-trottoir.001']} position={[-0.133, 1.102, -0.006]} />
        <mesh geometry={nodes.Cube001_0.geometry} material={materials['paves-trottoir']} position={[1.299, 1.102, -0.006]} />
        <mesh geometry={nodes.Circle004_0.geometry} material={materials.trottoir} position={[1.299, 1.102, -0.008]} scale={0.052} />
        <mesh geometry={nodes.Circle005_0.geometry} material={materials['trottoir.002']} position={[1.299, 3.589, -0.007]} scale={0.052} />
        <mesh geometry={nodes.Cube002_0.geometry} material={materials['paves-trottoir.002']} position={[1.299, 3.589, -0.006]} />
        <mesh geometry={nodes.TexturesCom_RoadsBarriers0011_4_S_0.geometry} material={materials['TexturesCom_RoadsBarriers0011_4_S.004']} position={[0.167, 0.585, 0.014]} rotation={[Math.PI / 2, 0.119, 0]} scale={0.057} />
        <mesh geometry={nodes.TexturesCom_RoadsBarriers0011_5_S_0.geometry} material={materials.TexturesCom_RoadsBarriers0011_5_S} position={[0.254, 0.592, 0.014]} rotation={[Math.PI / 2, 0.11, 0]} scale={0.057} />
        <mesh geometry={nodes.TexturesCom_RoadsBarriers0011_6_S_0.geometry} material={materials.TexturesCom_RoadsBarriers0011_6_S} position={[0.339, 0.599, 0.014]} rotation={[Math.PI / 2, 0.027, 0]} scale={0.056} />
        <mesh geometry={nodes.TexturesCom_RoadsBarriers0011_6_S002_0.geometry} material={materials['TexturesCom_RoadsBarriers0011_6_S.001']} position={[0.969, 0.91, 0.014]} rotation={[Math.PI / 2, 0.081, 0]} scale={0.056} />
        <mesh geometry={nodes.TexturesCom_RoadsBarriers0011_5_S002_0.geometry} material={materials['TexturesCom_RoadsBarriers0011_5_S.003']} position={[0.884, 0.903, 0.014]} rotation={[Math.PI / 2, 0.035, 0]} scale={0.057} />
        <mesh geometry={nodes.TexturesCom_RoadsBarriers0011_4_S002_0.geometry} material={materials['TexturesCom_RoadsBarriers0011_4_S.001']} position={[0.797, 0.895, 0.014]} rotation={[Math.PI / 2, 0.105, 0]} scale={0.057} />
        <mesh geometry={nodes.TexturesCom_RoadsBarriers0011_5_S003_0.geometry} material={materials['TexturesCom_RoadsBarriers0011_5_S.001']} position={[0.707, 0.904, 0.014]} rotation={[-Math.PI / 2, -0.032, Math.PI]} scale={0.057} />
        <mesh geometry={nodes.TexturesCom_RoadsBarriers0011_4_S003_0.geometry} material={materials['TexturesCom_RoadsBarriers0011_4_S.005']} position={[0.427, 0.621, 0.014]} rotation={[-Math.PI / 2, -0.07, -Math.PI]} scale={0.057} />
        <mesh geometry={nodes.TexturesCom_RoadsBarriers0011_4_S004_0.geometry} material={materials['TexturesCom_RoadsBarriers0011_4_S.003']} position={[0.919, -0.037, 0.014]} rotation={[-Math.PI / 2, -0.405, -Math.PI]} scale={0.057} />
        <mesh geometry={nodes.TexturesCom_RoadsBarriers0011_6_S003_0.geometry} material={materials['TexturesCom_RoadsBarriers0011_6_S.002']} position={[0.844, -0.086, 0.014]} rotation={[Math.PI / 2, 0.362, 0]} scale={0.056} />
        <mesh geometry={nodes.TexturesCom_RoadsBarriers0011_5_S004_0.geometry} material={materials['TexturesCom_RoadsBarriers0011_5_S.002']} position={[0.648, -0.176, 0.014]} rotation={[Math.PI / 2, 0.446, 0]} scale={0.057} />
        <mesh geometry={nodes.TexturesCom_RoadsBarriers0011_4_S005_0.geometry} material={materials['TexturesCom_RoadsBarriers0011_4_S.002']} position={[0.568, -0.212, 0.014]} rotation={[Math.PI / 2, 0.454, 0]} scale={0.057} />
        <mesh geometry={nodes.TexturesCom_RoadsBarriers0021_S_0.geometry} material={materials.TexturesCom_RoadsBarriers0021_S} position={[0.023, 2.498, 0.124]} rotation={[Math.PI / 2, 0.277, 0]} />
        <mesh geometry={nodes.TexturesCom_RoadsBarriers0021_S001_0.geometry} material={materials['TexturesCom_RoadsBarriers0021_S.001']} position={[0.813, 2.723, 0.124]} rotation={[Math.PI / 2, 0.277, 0]} />
        <mesh geometry={nodes.TexturesCom_RoadsBarriers0011_5_S005_0.geometry} material={materials['TexturesCom_RoadsBarriers0011_5_S.004']} position={[1.073, 0.931, 0.027]} rotation={[-Math.PI / 2, -0.032, Math.PI]} scale={0.057} />
        <mesh geometry={nodes.TexturesCom_RoadsBarriers0011_4_S006_0.geometry} material={materials.TexturesCom_RoadsBarriers0011_4_S} position={[0.071, 0.591, 0.027]} rotation={[-Math.PI / 2, -0.07, -Math.PI]} scale={0.057} />
        <mesh geometry={nodes.Plane001_0.geometry} material={materials.toile} position={[1.176, -0.021, 0.179]} />
        <mesh geometry={nodes.Plane_0.geometry} material={materials['structure-toile']} position={[1.176, -0.021, 0.179]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.Landscape_0.geometry} material={materials.monticule} position={[0.144, 0.365, -0.013]} />
        <mesh geometry={nodes.TexturesCom_MetalFences0005_S_0.geometry} material={materials.TexturesCom_MetalFences0005_S} position={[0.413, 2.629, 0.094]} rotation={[Math.PI / 2, 0.276, 0]} scale={[0.229, 0.23, 0.229]} />
        <mesh geometry={nodes.IVY_Curve_0.geometry} material={materials['ivy-tronc']} />
        <mesh geometry={nodes.IVY_Curve_1.geometry} material={materials['ivy-leaves']} />
        <mesh geometry={nodes.IVY_Curve001_0.geometry} material={materials['ivy-tronc.001']} />
        <mesh geometry={nodes.IVY_Curve001_1.geometry} material={materials['ivy-leaves.001']} />
        <mesh geometry={nodes.grass144_0.geometry} material={materials.grass} position={[0.435, -0.294, -0.013]} rotation={[1.552, -1.155, -0.033]} scale={0.027} />
        <mesh geometry={nodes.Icosphere366_0.geometry} material={materials.gravas} position={[0.493, -0.116, -0.016]} rotation={[0.018, 0.081, 1.382]} scale={0.005} />
        <mesh geometry={nodes.TexturesCom_NaturePlants0005_1_alphamasked_S050_0.geometry} material={materials.TexturesCom_NaturePlants0005_1_alphamasked_S} position={[0.501, -0.03, -0.014]} rotation={[1.607, 0.405, 0.043]} scale={0.053} />
        <mesh geometry={nodes.TexturesCom_NaturePlants0038_1_alphamasked_S041_0.geometry} material={materials.TexturesCom_NaturePlants0038_1_alphamasked_S} position={[0.495, -0.04, -0.015]} rotation={[1.408, 1.327, 0.179]} scale={0.063} />
        <mesh geometry={nodes.TexturesCom_NaturePlants0052_1_alphamasked_S134_0.geometry} material={materials.TexturesCom_NaturePlants0052_1_alphamasked_S} position={[0.491, -0.168, -0.014]} rotation={[-1.479, -0.131, -3.132]} scale={0.024} />
        <mesh geometry={nodes.Sphere_0.geometry} material={materials.ciel} position={[0, 0, -2.043]} rotation={[0, 0, -1.078]} scale={4.229} />
      </group>
    </group>
  )
}

useGLTF.preload('models/postwar_city/scene.gltf')
